### ISSUE TITLE
Road map download button bug

### ISSUE THREAD

**Issue by AlfiyaSiddique** [Opentek-Org/opentek#604]
### Description

The road map download button is not working. **It is not downloading the roadmap image**. I have figured out how to fix it so can you please assign me this issue under gssoc23 labels!!

### Screenshots

https://github.com/Opentek-Org/opentek/assets/86224794/9ef356ff-c0dc-495b-a475-bf59451a9db9

### Checklist

- [X] I have checked the [existing issues](https://github.com/Opentek-Org/opentek/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Opentek-Org/opentek/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)
- [X] I am a GSSoC'23 contributor
